fix file

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -1,10 +1,22 @@
 name: Build project and Run Lighthouse CI
 on: [push]
 jobs:
-  ci:
-    name: ci work flow
+  set-up:
+    name: setup
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v1
-      - uses: ./.github/actions/setup
-      - uses: ./.github/actions/lhci
+      - name: Use Node.js 10.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: 10.x
+      - name: npm run build
+        run: npm run build
+jobs:
+  lhci:
+    name: Lighthouse CI
+    runs-on: ubuntu-latest
+    steps:
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --config=./lighthouseci/.lighthouserc.json --upload.target=temporary-public-storage || echo "LHCI failed!"
